version: '3.7'

services:
  font-installer:
    image: ${IMAGE_NAME}:${VERSION:?No image version set}
    user: root
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.role == manager
    entrypoint: ["bash", "-c"]
    command:
      - |
        echo "Installing fonts..."
        
        # Add contrib and non-free repositories for Microsoft fonts
        echo "deb http://deb.debian.org/debian bookworm contrib non-free non-free-firmware" > /etc/apt/sources.list.d/contrib.list
        
        apt-get update
        
        # Accept Microsoft font license automatically
        echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | debconf-set-selections
        
        # Install fonts with better error handling
        echo "Installing Microsoft fonts..."
        apt-get install -y ttf-mscorefonts-installer || echo "Microsoft fonts failed to install"
        
        echo "Installing other font packages..."
        apt-get install -y \
          fonts-liberation \
          fonts-dejavu-core \
          fonts-dejavu-extra \
          fonts-noto \
          fonts-roboto \
          fontconfig || echo "Some font packages failed"
        
        echo "Checking what fonts are actually available..."
        find /usr/share/fonts -name "*.ttf" | head -20
        
        # Copy fonts to shared volume
        mkdir -p /shared-fonts
        cp -r /usr/share/fonts/truetype/* /shared-fonts/ 2>/dev/null || true
        cp -r /usr/share/fonts/TTF/* /shared-fonts/ 2>/dev/null || true
        
        # Create font cache
        fc-cache -fv /shared-fonts/
        
        # Fix permissions for frappe user (UID 1000)
        chown -R 1000:1000 /shared-fonts/
        
        echo "✅ Fonts installed successfully!"
        echo "Final font check:"
        fc-list | grep -E -i "(arial|times|verdana|liberation|dejavu|noto)" | head -20
    volumes:
      - shared-fonts:/shared-fonts

volumes:
  shared-fonts:
    name: ${BENCH_NAME:-erpnext}_shared_fonts